### ISSUE TITLE
[GAME] RemoveOutput not removing specified output

### ISSUE THREAD

**Issue by arbabf** [mapbase-source/source-sdk-2013#176] opened 2022-02-13 12:31 UTC
I have a `weapon_frag`, having the outputs `OnPlayerPickup` and `OnPlayerUse`, tied to a `logic_relay` (fast retrigger off). I want the player to either pick up or +use the entity; to do this, I added the output `RemoveOutput OnPlayerPickup` to itself when the player +uses the entity, but when all outputs on the `logic_relay` have fired, thus allowing any other `Trigger` inputs to it to fire, picking up the entity still fires the `OnPlayerPickup` output, and thus triggering the `logic_relay`.

Using a wildcard does not seem to help the issue, either.

![image](https://user-images.githubusercontent.com/34561149/153753110-3204a27a-5c34-4b9f-b7ec-b5b034d36c21.png)

**Comment by Blixibon** [comment] 2022-10-21 15:01
I tried reproducing this and the issue seems to be that `OnPlayerPickup` fires before `OnPlayerUse` does since they're on the same frame, despite the latter technically firing before the former.

I looked into the possibility of making outputs like `RemoveOutput` prioritize themselves on the queue, but outputs are separated from the queue in a way that makes that mostly infeasible. If I recall correctly you mentioned you already found a workaround, so I'm going to close this issue for the time being.

**Closed by Blixibon** 2022-10-21 15:01 UTC
Labels: Bug
